name: Run on Command

on:
  workflow_dispatch:

jobs:
  print-messages:
    runs-on: ubuntu-latest

     steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Step 1 - Run step1.py
        run: python3 step1.py

      - name: Step 2 - Run step2.py
        run: python3 step2.py

      - name: Step 3 - Run step3.py
        run: python3 step3.py
