name: Run on Command

on:
  workflow_dispatch:

jobs:
  print-messages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: 1. DICOM Loading
        run: |
          python3 step1.py
          python3 step1-1.py

      - name: 2. Implant Segmentation
        run: python3 step2.py

      - name: 3. Hip ROI Identification
        run: python3 step3.py
